site_name: sindre库
site_author: sindreyang
use_directory_urls: True


# 目录
nav:
  - 主页: index.md
  - 用法:
    - LMDB集成: lmdb.md
    - Win工具: win_tools.md
    - 3D: 3d.md

# 主题
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - search.highlight
  palette:
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# 插件
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [ sindre ]
          options:
            show_source: false
  - search:
      lang:
        - en
        - zh

# 拓展
extra:
  generator: false