site_name: sindre库
site_author: sindreyang
repo_url: https://github.com/SindreYang/sindre
use_directory_urls: True


# 目录
nav:
  - 关于: index.md
  - LMDB集成: lmdb.md
  - 三维算法: 3d.md
  - 模型部署: deploy.md
  - 通用工具: general.md
  - 测试报告: report.md
  - Windows系统工具: win_tools.md
  - API文档: api.md


# 主题
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - search.highlight
  palette:
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# 插件
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [ sindre ]
          options:
            show_source: false
  - search:
      lang:
        - en
        - zh

# 拓展
extra:
  generator: false