name: Clean Workflow Logs

on:
  schedule:
    - cron: "0 0 * * *" 
jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v6
        with:
          token: ${{ github.token }} # optional
          owner: ${{ github.repository_owner }} # optional
          repo: ${{ github.repository }} # optional
          runs_older_than: 3 # optional
          runs_to_keep: 1 # optional
