name: Deploy sindre to PyPi
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy_pypi:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build Wheel
        run: |
            python -m pip install -r requirements.txt
            python setup.py bdist_wheel
            git config --global url."https://${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"
            mkdocs gh-deploy --remote - name target - origin

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            password: ${{ secrets.PYPI_KEY }}
            packages-dir: dist/dist/
