name: Deploy sindre 
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # - name: Checkout main
      #   uses: actions/checkout@v2
      
    #   - name: Set up Python 3.8
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: 3.8

    #   - name: Build Wheel
    #     run: |
    #         python -m pip install -r requirements.txt
    #         python setup.py bdist_wheel
    #         mkdocs gh-deploy

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
            ref: gh-pages
      - name: Push Branch to Another Repository
        run: |
            git config --global user.name "SindreYang"
            git config --global user.email "yx@mviai.com"
            git config --global url."https://${{secrets.GH_TOKEN}}@github.com".insteadOf "https://github.com"
            git remote add target https://github.com/SindreYang/sindre.git
            git push target gh-pages:gh-pages

    #   - name: Publish distribution to PyPI
    #     uses: pypa/gh-action-pypi-publish@release/v1
    #     with:
    #         password: ${{ secrets.PYPI_KEY }}
    #         packages-dir: dist/dist/
